# Generated by Django 4.1.3 on 2022-11-02 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(choices=[('FPS', 'First-person shooter'), ('TPS', 'Third-person shooter'), ('RPG', 'Role-playing games'), ('MOBA', 'Multiplayer online battle arena')], max_length=10)),
                ('fsk', models.CharField(choices=[('0', 'Altersfreigabe ab 0 Jahren'), ('6', 'Altersfreigabe ab 6 Jahren'), ('12', 'Altersfreigabe ab 12 Jahren'), ('16', 'Altersfreigabe ab 16 Jahren'), ('18', 'Altersfreigabe ab 18 Jahren')], max_length=2)),
                ('erstellung', models.DateTimeField()),
                ('ersteller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ['genre', 'name'],
            },
        ),
    ]
