# Generated by Django 4.1.3 on 2022-11-07 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_rename_games_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='ersteller',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='game',
            name='erstellung',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
